version: "3.8"

services:
  update-stores:
    build: .
    container_name: update-stores
    restart: always
    ports:
      - "8003:8000"
    environment:
      - TZ=America/Lima
    # volumes:
    #   - ./logs:/app/logs
